#+TITLE: Homework Set 1
#+author: Jacob Bailey
#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{amssymb}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{fancyhdr}

#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\rhead{Homework 1, Math 532}
#+LATEX_HEADER:\lhead{Jake Bailey}
#+LATEX_HEADER:\rfoot{Page \thepage}

* Problem 1

Let $T_1$ and $T_2$ be topologies on a set $X$. Show that $T_1 \cap
T_2$ is also a topology on $X$. Give an example to show that $T_1\cup
T_2$ need not be a topology on $X$. 

Recall that by definition, $T_1$ and $T_2$ both, as topologies,
satisfy the following properties: 

- Both include $\emptyset$ and $X$
- Both are closed under arbitrary unions
- Both are closed under finite intersections

#+BEGIN_proof
Consider $T_3 = T_1 \cap T_2$. It is immediate that $T_3$ contains
both $\emptyset$ and $X$, since $T_1$ and $T_2$ do. 

Next, we consider unions of members of $T_3$. By definition, for a set
$U_{\alpha} \in T_3$, $U_{\alpha}$ must also be in $T_1$ and
$T_2$. Since both constituents are closed under unions, we have that
for any $U_{3} = \bigcup\limits_{\alpha \in J} U_{\alpha}$, $U_3$ is
also in $T_3$ by closedness of $T_1$ and $T_2$. Hence, $T_3$ is closed
under arbitrary unions.

Finally, we consider finite intersections. Again, by definition of
$T_3$, we have that for any set $U \in T_3$, $(U \in T_1)\ \text{and}\
(U \in T_2)$. Thus, for a set $V = \bigcap\limits_{\alpha \in
J}U_{\alpha}$, $J$ finite, $(V \in T_1)\ \text{and}\ (V \in
T_2)$. Hence, $V \in T_3$, and $T_3$ is closed under finite
intersections.

We have shown that $T_3$ is a collection of sets on $X$ which
satisfies the three properties of a topology. Hence, $T_3$ is a
topology on $X$. 
#+END_proof

For an example of how $T_1\cup T_2$ need not be a topology, consider
$\mathbb{R}_{std} \cup \mathbb{R}_l$. We choose the sets $(1,2)$ and
$[3,4)$, which are in $\mathbb{R}_{std}$ and $\mathbb{R}_l$,
respectively. However, their union $(1,2)\cup [3,4)$ is not in $T_3$,
since it is the union of the collections of sets, not the sets
themselves. Thus, $T_3$ isn't closed under unions, and cannot be a
topology.

* Problem 2

Show that the topologies of $\mathbb{R}_l$ and $\mathbb{R}_K$ are not
comparable.

#+BEGIN_proof
First, we recall the definition of $\mathbb{R}_K$: the topology
generated by the basis of sets $B = \{ (a,b) - K\ |\ a,b \in
\mathbb{R}\}$, where $K = \{ \frac{1}{n} |\ n \in \mathbb{N}\}$.

Given an element of the basis of $\mathbb{R}_l$, say $b_l =
[a,b)$. Then, choose $x = a$. Clearly, there is no open set in the
topology generated by $B_K$ that both contains $x$ and is a subset of
$[a,b)$.

Similarly, take $b_K = (-1, 1) - K$, and let $x = 0$. Then, there is
no element of $B_l$ that both contains $x$ and lies within $b_K$,
since there is a point $y = 1/n, n \in \mathbb{N}$ that lies
arbitrarily close to $x$ which is not in $b_K$. 

Thus, $\mathbb{R}_l$ and $\mathbb{R}_K$ are not comparable.
#+END_proof

* Problem 3

** Part a
Apply lemma 13.2 to show that the countable collection $B = \{
(a,b) |\ a<b,\ a,b \in \mathbb{Q}\}$ is a basis that generates
$\mathbb{R}_{std}$.

Lemma 13.2: Let $X$ be a topological space. Suppose that $C$ is a
collection of open sets, such that $\forall U \in X$ and $\forall x
\in U$, $\exists c \in C$ such that $x \in C \subseteq U$. Then $C$ is
a basis for the topology in $X$.

#+BEGIN_proof

Define $B_{\mathbb{Q}} = \{ (a,b) |\ a < b, a,b \in \mathbb{Q}\}$.

Let $U$ be in the topology generated by $B_{\mathbb{Q}}$. Then, $U$ is
some combination of finite unions and arbitrary intersections of
elements of $B_{\mathbb{Q}}$, which are all also open sets in
$\mathbb{R}_{std}$. Thus, $U \in \mathbb{R}_{std}$. 

Conversely, let $U$ be in $T_{std}$, and take $x \in U$. Then,
$\exists (a,b) \in \mathbb{R}$ such that $x \in (a,b) \subseteq
U$. Since $\mathbb{Q}$ is dense in $\mathbb{R}$, we can find $c,d$
such that $a < c < x < d < b$, and thus $x \in (c,d) \subseteq
U$. Thus, by lemma 13.2, our collection $B_{\mathbb{Q}}$ is a basis
for the standard topology in $\mathbb{R}$.

#+END_proof

** Part b
Show that the collection $C = \{[a,b)|\ a<b,\ a,b \in \mathbb{Q}\}$ is a
basis that generates a topology different from $\mathbb{R}_l$.

#+BEGIN_proof

Clearly, $C$ is a basis for a topology in $\mathbb{R}$, again by lemma
13.2. However, it cannot generate $[i,j), i,j
\not\in\mathbb{Q}$. $[i,j) \not\in C$, since $C$ contains only
intervals with rational endpoints. Further, we cannot construct
$[i,j)$ as $[a,b)\cap[c,d)$, since $[a,b)\cap[c,d) = [\text{max}(a,c),
\text{min}(b,d))$, and $a,b,c,d \in \mathbb{Q}$. Finally, we note that
we also cannot construct $[i,j)$ as a union of intervals $[a_i, b_i),
a_i, b_i \in\mathbb{Q}$, for the same reason as stated above. Since a
topology must be closed under arbitrary unions and finite
intersections, and we cannot construct $[i,j), i,j \not\in\mathbb{Q}$
from $C$, the topology generated by $C$ cannot be the lower limit
topology on $\mathbb{R}$.

#+END_proof

* Problem 4

Show that if $A$ is a basis for a topology on a set $X$, then the
topology generated by $A$ equals the intersection of all topologies on
$X$ that contain $A$. Prove the same if $A$ is a subbasis.

Lemma 13.1: The topology generated by $A$ is the collection of all
unions of all elements of $A$. 

#+BEGIN_proof

Let the intersection of all topologies containing $A$ be $T_x =
\bigcap\limits_{\alpha \in J}T_{\alpha}$. Since they contain $A$ and
are topologies, by property 2 of a topology, any $T_{\alpha}$ must be
closed under arbitrary unions. Thus, $T_A = \bigcup\limits_{\alpha \in
J} U_{\alpha}$, the topology generated by $A$ (by lemma 13.1), is in
any of the above $T_{\alpha}$. Therefore, $T_A \subseteq T_x$.

Conversely, $T_x$ is a topology, and closed under unions. Since $T_A
\subseteq T_x$, then there is no set $U \in T_x$ for which $U \not\in
T_A$. Assume there is. By our construction of $T_x$, this requires $U$
to be in every $T_{\alpha}$ on X. However, $T_A$ is a topology on $X$
which contains $A$, and thus must be one of the
$T_{\alpha}$. Therefore, $U \in T_A$, a contradiction. Hence, $\forall
U \in T_x, U \in T_A$, and $T_x \subseteq T_A$. Therefore, $T_x =
T_A$.

#+END_proof

Next, we prove that the topology generated by a subbasis $A$ equals
the intersection of all topologies on $X$ that contain $A$. 

Definition: A \textit{subbasis} $S$ for a topology on $X$ is a
collection of subsets of $X$ whose union equals $X$. The
\textit{topology generated by $S$} is defined to be the collection $T$
of all unions of finite intersections of elements of $S$.

#+BEGIN_proof

Any topology that contains $A$ must also contain the topology
generated by $A$, since any topology must be closed under arbitrary
unions and finite intersections (properties 2 and 3 of
topologies). Thus, the intersection of all topologies on $X$
containing $A$ must also include the topology generated by $A$. That
the two are equal then follows from the subsetting arguments above.

#+END_proof

