#+TITLE: Math 532 Notes
#+AUTHOR: Jake Bailey

#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \newtheorem{theorem}{Theorem}[section]
#+LATEX_HEADER: \newtheorem{lemma}{Lemma}[section]
#+LATEX_HEADER: \newtheorem{definition}{Definition}[section]
#+LATEX_HEADER: \newtheorem{question}{Question}[section]
#+LATEX_HEADER: \newtheorem{summary}{Summary}[section]

* Lecture 1 <2020-01-15 Wed>

Basic introductions to the course. Office hours M 2-3 (Math 220), TW
2-3 (Math 219), and by appointment. Book is Topology by Munkres. 

** Topological Spaces

What are open sets in $\mathbb{R}$? We know they can be intervals,
like $(1,2)$ or $(a,b)$. $\mathbb{R}$ itself is another example, as
well as its complement, $\emptyset$.

#+BEGIN_question
What questions does Topology answer. Which does it ask? 
#+END_question

#+BEGIN_question
What is the origin of the name "Point-Set Topology"?
#+END_question

The set of all open intervals defines the "standard topology" on
$\mathbb{R}$.

We'll also be concerned with homeomorphisms (Donuts + Coffee mugs). 

Much of "Point-Set Topology" is motivated by necessity from real analysis. 

Metrics induce a topology. A reasonable question in topology is "how
close is this space to being metrizable?"

#+BEGIN_summary
We'll cover fundamental Point-Set Topology as well as som algebraic
topology in this course. We begin with open sets in $\mathbb{R}$.
#+END_summary

** Class Outline
- Basics of Topology
- Waht is a topology
- Continuous functions
- Building new topologies
  - Product, Subspace, Metric, Quotient T's
- Connectedness
- Compactness
- Separation Axioms
- Metrizability
- Tychonoff's Theorem
- Topics in Algebraic Topology
  - Homotopy
  - Fundamental Groups
  - Boraz-Luanne?


** Back to Topology
#+BEGIN_definition 

Given a set $X$, a topology on $X$ is a collection $T$ of subsets of
$X$ with the following properties:

1) $\emptyset, X \in T$
2) If $X_{\alpha} \in T, \forall \alpha \in J$, then
   $\bigcup\limits_{\alpha \in J}X_{\alpha} \in T$. ($J$ arbitrary
   indices).
3) If $J$ is finite, then $\cap_{\alpha \in J}X_{\alpha} \in T$.

#+END_definition

Topologies are collections of sets that 
1) Contain the empty set and the whole space
2) Are closed under arbitrary unions
3) Are closed under finite intersections

#+BEGIN_question

Where/how does an infinite intersection break a topology? Why are
finite intersections the only kind allowed? 

#+END_question
#+BEGIN_summary

A topology is a collection of sets with three key properties

#+END_summary

** Topologies on $\mathbb{R}$
1) The standard topology, $T_{std}$.
2) The lower limit topology, $\mathbb{R}_l$
   1) Basis of elements as $[a,b)$
3) Any set $X$ has two topologies
   1) The discrete topology, $T = 2^X$
   2) The indiscrete topology, $T = \{\emptyset, X\}$


#+BEGIN_question 

Are there sets for which the discrete and indiscrete topologies are
equivalent?

#+END_question

** Example
Take $X = \{1,2,3\}$. Then, the following are topologies on $X$: $T =
\{\{1\},\{1,2\},X,\emptyset\}$, $T =
\{\{2\},\{1,2\},\{2,3\},X,\emptyset\}$. The following is not: $T =
\{\{1\},\{3\},X,\emptyset\}$.

#+BEGIN_summary 

Topologies can be formed on all sets, even ones we wouldn't categorize
with others, e.g. $\mathbb{R}$ vs $\mathbb{N}$, etc.

#+END_summary

* More on topological spaces <2020-01-17 Fri>
#+BEGIN_definition

Suppose that $T, T'$ are two topologies on $X$. If $T \subseteq T'$,
we say that $T'$ is \textit{finer} than $T$, and that $T$ is
\textit{coarser} than $T'$. We say that $T$ and $T'$ are comparable if
either is contained in the other. 

#+END_definition

#+BEGIN_definition

If $X$ is a set, a \textit{basis} for a topology on $X$ is a
collection $B$ of subsets such that 
1) $\forall x \in X, \exists b \in B$ such that $x \in b$.
2) If $b_1, b_2 \in B$, then $\exists b_3 \in B$ such that $b_3
   \subseteq b_1\cap b_2$.

#+END_definition

#+BEGIN_question 

Is the standard topology in $\mathbb{R}$ comparable with the lower
limit topology?

#+END_question

#+BEGIN_definition

A set $X$ along with a topology is called a \textit{topological
space}.

#+END_definition

#+BEGIN_definition

If $(X,T)$ is a topological space, than a set $Y\subseteq X$ is open
iff $Y \in T$. $Z\subseteq X$ is closed iff $Z\setminus X$ is
open. (Open means a set is a member of the topology). 

#+END_definition

** Example
$(\mathbb{R}, 2^{\mathbb{R}}). 

All sets in $\mathbb{R}$ are open, and they're also closed. 

$(\mathbb{R}, \{\emptyset, \mathbb{R}\})$.

Open sets are only $\emptyset, \mathbb{R}$. These are also the only
closed sets. 

$(\mathbb{R}, T_{std})$

$(0,5)$ is open. $\mathbb{R}\setminus (0,5)$ is closed.

Recall that $T_{std}$ is generated by the collection of open intervals
$(a,b)$ in $\mathbb{R}$. 

#+BEGIN_question

Do bases have to be minimal and/or orthonormal? Does that question
even make sense? 

#+END_question

#+BEGIN_question

Can we characterize topologies where open sets are also closed?

#+END_question

** Bases

The topology generated by a basis $B$ is defined as: $U$ is open in
$X$ if $\forall x \in U, \exists b \in B$ such that $x \in b \subseteq
U$.

To check is a set $U$ is open, 

1) Pick $x \in U$
2) Find $b\in B$ such that $x \in b \subseteq U$.



*** Example
Is $U = (0,5)\cup(15,20)$ open in $\mathbb{R}_{std}$? Yes. 

#+BEGIN_proof

Let $x \in U$. Then $x \in (0,5)$ or $x \in (15,20)$. Case 1: $x \in
(0,5)$. $(0,5) \in B$, and $(0,5) \subseteq (0,5)$. Case 2 is
equivalent.

#+END_proof

Checking for openness is a \textit{pointwise} operation. 

** Generating Topologies from Bases
#+BEGIN_theorem

Given a set $X$ and a basis $B$, the collection of sets $T$ generated
by $B$ as described above is a topology. 

#+END_theorem

#+BEGIN_proof

We look to show 3 properties:
1) $\emptyset, X \in T$
2) $T$ is closed under unions
3) $T$ is closed under finite intersections



1) $\emptyset \in T$ is vacuously true. For $X \in T$, Choose $U =
   X$. Then, $\exists b\in B$ such that $x \in b$. Satisfies clause 1.
2) Let $U_{\alpha} \in T$. For any $x \in \cup U_{\alpha}$, $\exists b
   \in B$ such that $x \in b, b \subseteq U_{\alpha}$, since $\exists
   \alpha'$ such that $x \in \cup U_{\alpha'}$, and $U_{\alpha'}$ is
   open.
3) For finite intersections: induction. Prove $T$ is closed under
   pairwise intersections, then assume $n$ intersections, prove $n +
   1$. Similar to unions, since $x \in U = U_1\cap U_2$ implies $x \in
   U_1$ and $x \in U_2$, so $\exists b \in B$ such that $x\in n$, and
   $b \subseteq U_1$ and $b \subseteq U_2$.


#+BEGIN_lemma 

Let $X$ be a set. Let $B$ be a basis for a topology on $X$. Then $T$
equals the collection of all unions of elements of $B$.

#+END_lemma

Proof by subsetting both ways. 

#+BEGIN_lemma

Let $(X,T)$ be a topological space. Suppose $C$ is a collection of
open sets of $X$ such that $\forall U \subseteq X$, $U$ open, and
$\forall x \in U$, $\exists c \in C$ such that $x \in c\subseteq
U$. Then $C$ is a basis for a topology on $X$. 

#+END_lemma






